### PR TITLE
Add linters job

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck

**Review by TristanCacqueray — COMMENTED** [review]
+2

**Review by TristanCacqueray — COMMENTED** [review]
this is a review

**Review by TristanCacqueray — COMMENTED** [review]
lgtm

**Review by morucci — APPROVED** [review]

**Review by morucci — APPROVED** [review]

**Review by morucci — APPROVED** [review]

**Review by morucci — APPROVED** [review]

**Pull request merged**
